server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        index index.html;
    }

    location /api/products {
        proxy_pass http://product-service:5000/;
    }

    location /api/cart {
        proxy_pass http://cart-service:5001/;
    }

    location /api/orders {
        proxy_pass http://order-service:5002/;
    }
}
