apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-service
  namespace: ecommerce
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cart-service
  template:
    metadata:
      labels:
        app: cart-service
    spec:
      containers:
        - name: cart-service
          image: 488627018883.dkr.ecr.us-east-2.amazonaws.com/atc-tech-store-cart-service:v1
          ports:
            - containerPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: cart-service
  namespace: ecommerce
spec:
  type: ClusterIP
  selector:
    app: cart-service
  ports:
    - port: 5001
      targetPort: 5001
